const projects={
 fitnesswatch:{"title": "Guided 5K Workout Experience", "subtitle": "A focused watch experience, supported by a companion app.", "image": "fitness-watch-2.png", "tags": "Design case study \u00b7 Wearable UX \u00b7 Companion app", "context": "A fitness brand design case study exploring a guided 5K run across a watch and phone. The challenge: keep the runner informed without competing for their attention.", "contribution": "I prioritized large type, high contrast, and a clear hierarchy on the watch, with pace as the primary metric. Setup and deeper analytics stay on the phone, while the watch supports starting, running, checking progress, responding to feedback, and reviewing a quick finish summary.", "focus": ["Readability over density: keep the watch focused on information useful in the moment", "Pace alerts and milestones: concise feedback supported by visual and haptic cues", "Accessible interaction: icons, labels, hierarchy, and larger controls rather than color alone"], "galleryTitle": "Workout flow and design rationale", "gallery": [{"image": "fitness-watch-1.png", "caption": "Case study overview \u00b7 Phone setup, run summary, watch states, and design rationale"}, {"image": "fitness-watch-2.png", "caption": "Watch flow \u00b7 Ready, active run, pace alert, milestone, pause, and finish summary"}]},
 figmaprocess:{"title": "My Design Process in Figma", "subtitle": "From audience questions to interface decisions.", "image": "figma-process-1.png", "tags": "Figma \u00b7 UX strategy \u00b7 Information architecture \u00b7 Interface design", "context": "A sample of my own design process, using the Croquet website to connect audience needs, product messaging, navigation, and interface layouts.", "contribution": "I mapped different audiences and their questions, outlined the customer journey, organized the site structure, and translated those decisions into navigation and annotated page layouts in Figma.", "focus": ["Understand who the experience serves and what they need", "Organize the journey, content, and navigation", "Translate the structure into clear interface layouts"], "galleryTitle": "The process, step by step", "gallery": [{"image": "figma-process-1.png", "caption": "Audience mapping \u00b7 Different users, questions, and product needs"}, {"image": "figma-process-4.png", "caption": "Journey mapping \u00b7 Awareness, consideration, acquisition, service, and loyalty"}, {"image": "figma-process-2.png", "caption": "Information architecture \u00b7 Site structure and navigation hierarchy"}, {"image": "figma-process-3.png", "caption": "Navigation design \u00b7 Translating the structure into a platform menu"}, {"image": "figma-process-5.png", "caption": "Annotated hero layout \u00b7 Messaging, calls to action, and interactive demo"}, {"image": "figma-process-6.png", "caption": "Annotated content layouts \u00b7 Implementation, benefits, and product features"}]},
 croquetworld:{"title": "Croquet API Keys & World Dashboard", "subtitle": "One workspace for worlds, people, and API access.", "image": "croquet-world-1.png", "tags": "Developer experience \u00b7 Dashboard design \u00b7 World management", "context": "A Croquet dashboard bringing world management, users, API keys, and account administration into a shared interface.", "contribution": "The screens show workflows for finding and entering worlds, exporting worlds, managing user roles and requests, reviewing API key details, and maintaining profile, company, and billing information.", "focus": ["World discovery and management", "User roles, membership requests, and API access", "A consistent workspace for account and billing tasks"], "galleryTitle": "World dashboard screens", "gallery": [{"image": "croquet-world-1.png", "caption": "Worlds dashboard \u00b7 Search, create, export, and enter worlds"}, {"image": "croquet-world-2.png", "caption": "General settings \u00b7 Company and address information"}, {"image": "croquet-world-3.png", "caption": "Profile settings \u00b7 Identity, password, and email verification"}, {"image": "croquet-world-4.png", "caption": "Plans and billing \u00b7 Subscription, payment details, and invoices"}, {"image": "croquet-world-5.png", "caption": "User management \u00b7 Roles and membership requests"}, {"image": "croquet-world-6.png", "caption": "Expanded user details \u00b7 Status and company membership"}, {"image": "croquet-world-7.png", "caption": "API keys \u00b7 Key details, members, and URL configuration"}]},
 croquetapi:{title:'Croquet API Key Tool',subtitle:'A developer-facing workspace for API access.',image:'croquet-api-1.png',tags:'Developer experience · Product design · API tools',context:'A key generator and management tool for developers building with Croquet’s API.',contribution:'The interface brings development and production keys together, with key creation, region selection, URL restrictions, copy controls, and key management actions. Related screens cover account settings, security, plans, and billing.',focus:['Development and production key workflows','Contextual guidance for URL restrictions','Account, security, and billing interfaces'],galleryTitle:'Developer portal screens',gallery:[{image:'croquet-api-1.png',caption:'API key dashboard · Development and production key management'},{image:'croquet-api-2.png',caption:'New API key · Naming, regions, URL restrictions, and contextual guidance'},{image:'croquet-api-3.png',caption:'Plan and billing · Usage, subscription options, payments, and invoices'},{image:'croquet-api-4.png',caption:'Account settings · Developer details and password validation'}]},

 juniper:{galleryTitle:'Navigation across screens',gallery:[{image:'juniper-nav-1.png',caption:'Desktop navigation · Solutions mega menu and country/language selection'},{image:'juniper-nav-2.png',caption:'Mobile navigation · Nested solution categories and expandable menus',mobile:true}],title:'Juniper Networks',subtitle:'A clearer path through enterprise navigation.',image:'2.png',tags:'UX · Information architecture · Frontend engineering',context:'Juniper’s enterprise navigation supports 500k+ monthly users and needs to help people find their way through a large, complex web experience.',contribution:'I led UX strategy, information architecture, and frontend architecture for Juniper’s navigation. I built scalable React and TypeScript components, reusable libraries, and design tokens using Storybook and AEM, partnered with designers on Figma-to-code implementation, and led WCAG 2.2 accessibility engineering across navigation and forms.',focus:['Organizing navigation around clearer paths','Connecting UX decisions with frontend implementation','Keeping accessibility and consistency in view']},
 analytics:{galleryTitle:'Operational data interfaces',gallery:[{image:'coppertree-1.png',caption:'Points table · Building, system, equipment, tags, and metadata filters'},{image:'coppertree-2.png',caption:'Dashboard · Configurable chart widgets and summary metrics'}],title:'Coppertree Analytics',subtitle:'Turning complex data into a usable interface.',image:'1.png',tags:'Product design · Frontend development · Data visualization',context:'Building and energy management generates complex data. Operational teams need an interface that helps them understand it.',contribution:'I designed and developed a smart building analytics dashboard with real-time performance data and customizable KPI views. I translated UX specifications into responsive production interfaces using Angular, TypeScript, and SCSS. Frontend improvements increased engagement by 15% year-over-year, and I participated in A/B testing with product, design, and engineering teams.',focus:['Dashboard architecture and visual hierarchy','UX and UI design for operational workflows','Frontend implementation and data visualization']},
 microverse:{gallery:[{image:'microverse-1.png',caption:'Object editor · Properties and behavior controls'},{image:'microverse-2.png',caption:'Earlier object editing interface'},{image:'microverse-3.png',caption:'Onboarding · Avatar and nickname selection'},{image:'microverse-4.png',caption:'In-world navigation, sharing, and workspace controls'}],title:'Microverse',subtitle:'Interfaces for a world shared in real time.',image:'microverse-cover.png',tags:'3D UX · Frontend · Real-time collaboration',context:'Croquet’s Microverse is an experimental, persistent multiplayer 3D environment.',contribution:'I contributed UX and UI development, working on avatar controls, interface performance, rendering optimizations, and real-time user feedback integration.',focus:['Avatar controls and user feedback','UI performance in a 3D environment','Rendering optimizations for shared experiences']},
 inkflow:{title:'Inkflow',subtitle:'A workspace for the business behind the art.',tags:'React · TypeScript · Vite · Tailwind CSS · Supabase',context:'An independent tattoo studio app in development, bringing clients and appointments into one workspace.',contribution:'The current implementation includes searchable client records, client detail panels, appointment creation, and Supabase-backed client and appointment data. It also includes a messages panel and form-builder preview.',focus:['Client records and appointment management','A dark studio dashboard with focused work areas','React and TypeScript with Supabase-backed data'],live:'https://tattoo-booking-app-kappa.vercel.app/',github:'https://github.com/intrqu/tattoo-booking-app'},
 universal:{galleryTitle:'Audio sync interfaces',gallery:[{image:'universal-audio-1.png',caption:'Audio Sync Dashboard · Device delay, volume, and enable controls'},{image:'universal-audio-2.png',caption:'Mobile audio states · Enable audio, test audio, and playback'}],title:'Universal Studios',subtitle:'An internal tool for Universal Studios’ Harry Potter experience.',image:'3.png',tags:'Design · UX · Development',context:'An internal tool for Universal Studios’ Harry Potter experience.',contribution:'I worked with Universal Studios on the Harry Potter internal tool. The project images include audio synchronization interfaces for managing device delay, volume, and playback states.',focus:['Internal product interfaces','Audio synchronization controls across devices','Device status and mobile playback states']},
 backroad:{title:'Backroad Mapbooks',subtitle:'Selected interface work.',image:'7.png',tags:'Design · UX · Development'},
 corridor:{title:'Corridor',subtitle:'Selected interface work.',image:'8.jpg',tags:'Design · UX · Development'},
 croquetweb:{title:'Croquet Website Redesign',subtitle:'A playful introduction to real-time collaboration.',image:'croquet-website-computer.png',galleryTitle:'Website design',gallery:[{image:'croquet-website-design.png',caption:'Homepage design · Microverse introduction and product storytelling'}],tags:'Design · UX · Frontend development',context:'A platform website and developer portal introducing Croquet’s real-time collaborative technology.',contribution:'I led the UX/UI direction and frontend implementation, focusing on product storytelling, responsive design, motion, and developer-focused usability.',focus:['A playful visual identity for a complex product','Clear product storytelling and developer-focused UX','Responsive frontend implementation and motion']},
 kyndryl:{title:'Kyndryl Website Redesign',subtitle:'Selected website redesign work.',image:'kyndryl-computer.png',galleryTitle:'Website design',gallery:[{image:'kyndryl-design.png',caption:'Full page design · AI solutions, services, and platform content'}],tags:'Design · UX · Development'},
 greenlight:{title:'Greenlight',subtitle:'A shared workspace for real-time collaboration.',image:'greenlight-1.png',tags:'Collaborative UX · Frontend · Croquet Virtual DOM',github:'https://github.com/croquet/greenlight-core',context:'Greenlight is a browser-based collaboration workspace. Each room provides a large two-dimensional canvas where participants can create and arrange collaborative apps, notes, images, and web pages together.',contribution:'The interface brings a shared canvas, content tools, video participants, chat, and presentation controls into one workspace. The supplied design screens also show organization members and shared room management.',focus:['Shared rooms and flexible canvas tools for working together','Browser DOM elements and embedded apps, powered by Croquet’s synchronized model/view architecture','Built on Croquet Virtual DOM with native JavaScript modules, CSS, and SVG interface assets'],galleryTitle:'Collaborative workspace and room management',gallery:[{image:'greenlight-1.png',caption:'Annotated workspace · Tools, participants, navigation, and presentation modes'},{image:'greenlight-2.png',caption:'Product mockup · Shared documents, media, and video collaboration'},{image:'greenlight-3.png',caption:'Organization dashboard · Members, shared rooms, and room creation'}]}
};
// Display each screenshot once: the main image already appears above the gallery.
Object.values(projects).forEach(project=>{if(project.gallery)project.gallery=project.gallery.filter(item=>item.image!==project.image)});
const dialog=document.getElementById('project-dialog');let opener;
const projectSlugs={juniper:'juniper-networks',analytics:'coppertree-analytics',microverse:'croquet-microverse',croquetweb:'croquet-website-redesign',croquetworld:'croquet-world-dashboard',croquetapi:'croquet-api-key-tool',figmaprocess:'figma-design-process',fitnesswatch:'guided-5k-workout',universal:'universal-studios',backroad:'backroad-mapbooks',corridor:'corridor',kyndryl:'kyndryl-website-redesign',greenlight:'greenlight',inkflow:'inkflow'};
function projectHash(key){return '#project/'+projectSlugs[key]}

function openProject(key,button,syncUrl=true){const p=projects[key];if(!p)return;opener=button;if(syncUrl&&location.hash!==projectHash(key))history.pushState(null,'',projectHash(key));document.getElementById('project-content').innerHTML=`<div class="case-heading"><p class="eyebrow">${p.tags}</p><h2 id="dialog-title">${p.title}</h2><p class="case-subtitle">${p.subtitle}</p></div>${p.image?`<div class="case-image"><img src="assets/${p.image}" alt="${p.title} project interface"></div>`:'<div class="case-inkflow">inkflow®<small>TATTOO STUDIO APP · IN DEVELOPMENT</small></div>'}${p.context?`<div class="case-body"><section><span class="eyebrow">THE CONTEXT</span><p>${p.context}</p></section><section><span class="eyebrow">${['inkflow','croquetapi','croquetworld','greenlight'].includes(key)?'THE INTERFACE':'MY CONTRIBUTION'}</span><p>${p.contribution}</p></section><section><span class="eyebrow">PROJECT FOCUS</span><ul>${p.focus.map(f=>`<li>${f}</li>`).join('')}</ul></section></div>`:''}${p.gallery?`<section class="case-gallery"><h3>${p.galleryTitle || 'Inside the Microverse'}</h3><div>${p.gallery.map(g=>`<figure class="${g.mobile ? 'mobile-screenshot' : ''}"><a href="assets/${g.image}" target="_blank" rel="noopener" aria-label="Open full-size screenshot: ${g.caption}"><img src="assets/${g.image}" alt="${g.caption}" loading="lazy"></a><figcaption>${g.caption}<span>Open full size</span></figcaption></figure>`).join('')}</div></section>`:''}${p.live?`<a class="case-code live-demo" href="${p.live}" target="_blank" rel="noopener">Try the live app</a>`:''}${p.github?`<a class="case-code" href="${p.github}" target="_blank" rel="noopener">Explore the code on GitHub</a>`:''}<div class="case-footer"><button type="button" data-copy-project="${key}">Copy project link</button><button type="button" data-next="${Object.keys(projects)[(Object.keys(projects).indexOf(key)+1)%Object.keys(projects).length]}">Next project</button><button type="button" data-close>Back to selected work</button></div>`;if(!dialog.open){dialog.showModal();document.body.classList.add('dialog-open')}dialog.scrollTop=0;}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project,b)));
function closeProject(syncUrl=true){if(syncUrl&&location.hash.startsWith('#project/'))history.replaceState(null,'','#work');dialog.close();document.body.classList.remove('dialog-open');opener?.focus()}
document.getElementById('close-project').addEventListener('click',closeProject);
dialog.addEventListener('cancel',event=>{event.preventDefault();closeProject()});
dialog.addEventListener('click',e=>{if(e.target===dialog)closeProject();const next=e.target.closest('[data-next]');if(next)openProject(next.dataset.next,opener);if(e.target.closest('[data-close]'))closeProject()});

document.querySelectorAll('[data-highlight-project]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();openProject(link.dataset.highlightProject,link)}));

const playHero=document.querySelector('.hero');
const weirdButton=document.getElementById('make-weird');
const playStatus=document.getElementById('play-status');
const creature=document.querySelector('.hero-creature');
const calmMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
weirdButton.addEventListener('click',()=>{const active=playHero.classList.toggle('is-weird');weirdButton.setAttribute('aria-pressed',String(active));weirdButton.innerHTML=active?'Back to earth <span aria-hidden="true">↩</span>':'Make it weird <span aria-hidden="true">✳</span>';playStatus.textContent=active?'Night flight activated. Follow the bat ✦':'A serious toolkit. A curious human.';});
let creatureFrame=0;
playHero.addEventListener('pointermove',event=>{if(calmMotion.matches||event.pointerType!=='mouse')return;cancelAnimationFrame(creatureFrame);creatureFrame=requestAnimationFrame(()=>{const box=playHero.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;creature.style.transform=`translate(${x*65}px, ${y*45}px) rotate(${12+x*20}deg)`;});});
function settleCreature(){cancelAnimationFrame(creatureFrame);creature.style.transform='rotate(12deg)';}
playHero.addEventListener('pointerleave',settleCreature);calmMotion.addEventListener('change',settleCreature);

function syncProjectFromUrl(){const slug=location.hash.replace(/^#project\//,'');const key=Object.keys(projectSlugs).find(key=>projectSlugs[key]===slug);if(key)openProject(key,document.querySelector(`[data-project="${key}"]`),false);else if(dialog.open)closeProject(false)}
window.addEventListener('popstate',syncProjectFromUrl);window.addEventListener('hashchange',syncProjectFromUrl);syncProjectFromUrl();
dialog.addEventListener('click',async event=>{const button=event.target.closest('[data-copy-project]');if(!button)return;const url=new URL(location.href);url.hash=projectHash(button.dataset.copyProject);try{await navigator.clipboard.writeText(url.href);button.textContent='Link copied'}catch{button.textContent='Copy the URL from your address bar'}});
